samples/config/routes.rb
AdaptivePaymentsSamples::Engine.routes.draw do
  post  "adaptive_payments/ipn_notify" => "adaptive_payments#ipn_notify", :as => :ipn_notify
  match "adaptive_payments(/:action)",  :controller => "adaptive_payments", :as => :adaptive_payments
  root :to => "adaptive_payments#index"
end

samples/app/models/adaptive_payments_samples/api_form_builder.rb
module AdaptivePaymentsSamples
  class APIFormBuilder < SimpleForm::FormBuilder
    def fields_for(member_name, member_object = nil, &block)
      member_object ||= ( object.send(member_name) || object.send("#{member_name}=", {}))
      member_options = object.class.members[member_name.to_sym]
      if member_options[:array]
        fields = []
        member_object.each_with_index do |obj, index|
          fields << super(member_name, obj, :index => index, &block)
        end
        fields.join.html_safe
      else
        super(member_name, member_object, &block)
      end
    end
    alias_method :simple_form_for, :fields_for
    alias_method :association, :fields_for

    def input(member_name, options = {})
      super(member_name, api_input_options(member_name, options))
    end

    def api_input_options(member_name, options = {})
      member_options      = object.class.members[member_name.to_sym]
      options[:label]   ||= member_name.to_s.underscore.humanize
      options[:wrapper] ||= :api_sample_form
      options[:required]  = !!member_options[:required] if options[:required].nil?
      if member_options[:type] < PayPal::SDK::Core::API::DataTypes::Enum
        options[:as] = ( member_options[:array] ? :check_boxes : :select )
        options[:collection] = member_options[:type].options
      elsif member_options[:type] == PayPal::SDK::Core::API::DataTypes::SimpleTypes::Boolean
        options[:as] = :select
        options[:collection] = [ true, false ]
      end
      options
    end
  end
end

samples/app/controllers/adaptive_payments_samples/adaptive_payments_controller.rb
require_dependency "adaptive_payments_samples/application_controller"

module AdaptivePaymentsSamples
  class AdaptivePaymentsController < ApplicationController
    include PayPal::SDK::AdaptivePayments

    def index
      redirect_to :action => :pay
    end

    def ipn_notify
      if PayPal::SDK::Core::API::IPN.valid?(request.raw_post)
        logger.info("IPN message: VERIFIED")
        render :text => "VERIFIED"
      else
        logger.info("IPN message: INVALID")
        render :text => "INVALID"
      end
    end

    def cancel_preapproval
      @cancel_preapproval = api.build_cancel_preapproval(params[:CancelPreapprovalRequest] || default_api_value)
      @cancel_preapproval_response = api.cancel_preapproval(@cancel_preapproval) if request.post?
    end

    def confirm_preapproval
      @confirm_preapproval = api.build_confirm_preapproval(params[:ConfirmPreapprovalRequest] || default_api_value)
      @confirm_preapproval_response = api.confirm_preapproval(@confirm_preapproval) if request.post?
    end

    def convert_currency
      @convert_currency = api.build_convert_currency(params[:ConvertCurrencyRequest] || default_api_value)
      @convert_currency_response = api.convert_currency(@convert_currency) if request.post?
    end

    def execute_payment
      @execute_payment = api.build_execute_payment(params[:ExecutePaymentRequest] || default_api_value)
      @execute_payment_response = api.execute_payment(@execute_payment) if request.post?
    end

    def get_allowed_funding_sources
      @get_allowed_funding_sources = api.build_get_allowed_funding_sources(params[:GetAllowedFundingSourcesRequest] || default_api_value)
      @get_allowed_funding_sources_response = api.get_allowed_funding_sources(@get_allowed_funding_sources) if request.post?
    end

    def get_payment_options
      @get_payment_options = api.build_get_payment_options(params[:GetPaymentOptionsRequest] || default_api_value)
      @get_payment_options_response = api.get_payment_options(@get_payment_options) if request.post?
    end

    def payment_details
      @payment_details = api.build_payment_details(params[:PaymentDetailsRequest] || default_api_value)
      @payment_details_response = api.payment_details(@payment_details) if request.post?
    end

    def pay
      @pay = api.build_pay(params[:PayRequest] || default_api_value)
      @pay.ipnNotificationUrl ||= ipn_notify_url
      @pay.returnUrl ||= adaptive_payments_url(:pay)
      @pay.cancelUrl ||= adaptive_payments_url(:pay)
      @pay_response = api.pay(@pay) if request.post?
    end

    def preapproval_details
      @preapproval_details = api.build_preapproval_details(params[:PreapprovalDetailsRequest] || default_api_value)
      @preapproval_details_response = api.preapproval_details(@preapproval_details) if request.post?
    end

    def preapproval
      @preapproval = api.build_preapproval(params[:PreapprovalRequest] || default_api_value)
      @preapproval.ipnNotificationUrl ||= ipn_notify_url
      @preapproval.returnUrl ||= adaptive_payments_url(:preapproval)
      @preapproval.cancelUrl ||= adaptive_payments_url(:preapproval)
      @preapproval_response = api.preapproval(@preapproval) if request.post?
    end

    def refund
      @refund = api.build_refund(params[:RefundRequest] || default_api_value)
      @refund_response = api.refund(@refund) if request.post?
    end

    def set_payment_options
      @set_payment_options = api.build_set_payment_options(params[:SetPaymentOptionsRequest] || default_api_value)
      @set_payment_options_response = api.set_payment_options(@set_payment_options) if request.post?
    end

    def get_funding_plans
      @get_funding_plans = api.build_get_funding_plans(params[:GetFundingPlansRequest] || default_api_value)
      @get_funding_plans_response = api.get_funding_plans(@get_funding_plans) if request.post?
    end

    def get_available_shipping_addresses
      @get_available_shipping_addresses = api.build_get_available_shipping_addresses(params[:GetAvailableShippingAddressesRequest] || default_api_value)
      @get_available_shipping_addresses_response = api.get_available_shipping_addresses(@get_available_shipping_addresses) if request.post?
    end

    def get_shipping_addresses
      @get_shipping_addresses = api.build_get_shipping_addresses(params[:GetShippingAddressesRequest] || default_api_value)
      @get_shipping_addresses_response = api.get_shipping_addresses(@get_shipping_addresses) if request.post?
    end

    def get_user_limits
      @get_user_limits = api.build_get_user_limits(params[:GetUserLimitsRequest] || default_api_value)
      @get_user_limits_response = api.get_user_limits(@get_user_limits) if request.post?
    end

    private

    def api
      @api ||= API.new
    end
  end
end

samples/app/controllers/adaptive_payments_samples/application_controller.rb
module AdaptivePaymentsSamples
  class ApplicationController < ActionController::Base

    def default_api_value
      t("#{service_name}.#{service_action}", :default => {})
    end

    def service_name
      params[:controller].gsub(/^.*\//, "")
    end

    def service_action
      params[:action]
    end
    helper_method :service_action, :service_name

  end
end

samples/app/helpers/adaptive_payments_samples/adaptive_payments_helper.rb
module AdaptivePaymentsSamples
  module AdaptivePaymentsHelper
  end
end

samples/app/helpers/adaptive_payments_samples/application_helper.rb
module AdaptivePaymentsSamples
  module ApplicationHelper
    def active_li(display, link_path, options = {})
      active_menu = options.delete(:match_path) ? request.path =~ Regexp.new(link_path) : request.path == link_path
      content_tag(:li, :class => active_menu ? "active" : "") do
        link_to(display, link_path, options)
      end
    end

    def active_li_regexp(display, link_path, options = {})
      active_li(display, link_path, options.merge(:match_path => true))
    end

    def api_form_for(object, *args, &block)
      options         = args.extract_options!
      options[:as]  ||= api_class_name(object.class)
      simple_form_for(object, *(args << options.merge(:builder => APIFormBuilder, :wrapper => :api_sample_form)), &block)
    end

    def generate_code(api_request, api_response)
      request_hash= api_request.to_hash(:namespace => false, :attribute => false)
      request_hash.delete(:Version)
      # request_hash  = get_dotted_hash(request_hash)
      response_hash = api_response.to_hash(:namespace => false, :attribute => false)
      ruby_code   = render("ruby_code.rb", :request_hash => request_hash, :response_hash => response_hash)
      ruby_code.html_safe
    end

    def get_dotted_hash(hash, prefix = "", values = {})
      max_lenght  = Hash[hash.select{|k, v| !(v.is_a? Hash or v.is_a? Array) }].keys.map(&:size).max
      hash.each do |key, value|
        if value.is_a? Hash
          get_dotted_hash(value, "#{prefix}#{key}.", values)
        elsif value.is_a? Array and value[0].is_a? Hash
          value.each_with_index do |array_value, index|
            get_dotted_hash(array_value, "#{prefix}#{key}[#{index}].", values)
          end
        elsif !value.nil?
          k = sprintf("%s%-#{max_lenght}s", prefix, key)
          values[k] = value
        end
      end
      values
    end

    def format_hash(hash)
      entries = hash.map do |key, value|
        "#{key.to_sym.inspect} => " +
          if value.is_a? Hash and value.size > 0
            format_hash(value)
          elsif value.is_a? Array and value[0].is_a? Hash
            "[" + value.map{|v| format_hash(v) }.join(",") + "]"
          else
            value.to_json
          end
      end
      indent_hash_entries(entries)
    end

    def indent_hash_entries(entries)
      if entries.size > 0
        "{\n" + entries.join(",\n").gsub(/^/, "  ") + " }"
      else
        "{}"
      end
    end

    def api_class_name(klass)
      klass.name.gsub(/^.*::/, "")
    end
  end
end

samples/app/views/adaptive_payments_samples/application/_api_response.html.haml
%div#response
  %p
    %b Ruby Code:
    = CodeRay.scan(generate_code(request, response), "ruby").div.html_safe
  %p
    %b Request:
    = CodeRay.scan(request.to_hash(:symbol => false).to_yaml, "yaml").div.html_safe
  %p
    %b Response:
    = CodeRay.scan(response.to_hash(:symbol => false).to_yaml, "yaml").div.html_safe

samples/app/views/adaptive_payments_samples/application/_hash_block.rb.erb
<% hash.each do |key, value| -%>
  <% if value.is_a? Hash -%>
<%= space %><%= key %> do
<%= render "hash_block.rb", :space => space + "  ", :hash => value %>
<%= space %>end
  <% elsif value.is_a? Array and value[0].is_a? Hash -%>
    <% value.each_with_index do |array_value, index| -%>
<%= space %><%= key %>[<%= index %>] do
<%= render "hash_block.rb", :space => space + "  ", :hash => array_value %>
<%= space %>end
    <% end -%>
  <% else -%>
<%= space %>self.<%= key %> = <%= value.to_json.html_safe %>
  <% end -%>
<% end -%>

samples/app/views/adaptive_payments_samples/application/_header.html.haml
.navbar.navbar-fixed-top
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .pull-right
        = link_to "Source on GitHub", "https://github.com/paypal/adaptivepayments-sdk-ruby", :class => "btn btn-small"
        %span.btn.btn-info.btn-small.disabled Click Submit to Generate Code !
      %a.brand{:href => "#"} PayPal SDK
      .nav-collapse.collapse
        %ul.nav
          = active_li_regexp "Adaptive Payments", adaptive_payments_path

samples/app/views/adaptive_payments_samples/application/_ruby_code.rb.erb
require 'paypal-sdk-<%= service_name.gsub("_", "") %>'
@api = PayPal::SDK::<%= service_name.camelize %>::API.new

# Build request object
@<%= service_action %> = @api.build_<%= service_action %>(<%=raw format_hash(request_hash) %>)

# Make API call & get response
@<%= service_action %>_response = @api.<%= service_action %>(@<%= service_action %>)

# Access Response
<% response_hash.each do |key, value| -%>
@<%= service_action %>_response.<%= key %>
<% end -%>

samples/app/views/adaptive_payments_samples/application/_sidebar.html.erb
<ul class="nav nav-list bs-docs-sidenav ">
  <%= active_li "Home",  "/" %>
</ul>

samples/app/views/adaptive_payments_samples/application/_token.html.haml
%legend Autherization
.control-group.string.optional
  = label_tag :token, "Token", :class => "string optional control-label"
  .controls
    = text_field_tag :token, params[:token] || @api.config.token

.control-group.string.optional
  = label_tag :token_secret, "Token Secret", :class => "string optional control-label"
  .controls
    = text_field_tag :token_secret, params[:token_secret] || @api.config.token_secret